version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-init-py:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo-init-py
    restart: on-failure
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_HOST=host.docker.internal
    command: python /app/mongo-init/init-mongo.py
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataplane-api
    restart: always
    depends_on:
      - mongodb
      - mongo-init-py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
      - API_TOKEN=${API_TOKEN}
      - MONGODB_URL=mongodb://host.docker.internal:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo-seeder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo-seeder
    restart: on-failure
    depends_on:
      - mongo-init-py
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://host.docker.internal:27017
    command: python /app/run_seeders.py
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_data: 